name = "twoitter"
main = "src/index.ts"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "twoitter.meowrhino.studio", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "twoitter-db"
database_id = "9fec7a62-ec30-4b2d-9eeb-4e1e0caf5552"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "twoitter-storage"
